### ISSUE TITLE
如何控制文档中组件的显示顺序

### ISSUE THREAD

**Issue by funlee** [worldzhao/react-ui-library-tutorial#11]
![image](https://s3.ax1x.com/2020/12/11/rAAV9P.png)

我想控制这些组件的显示顺序，怎么弄呢

**Comment by worldzhao** [comment]
![image](https://user-images.githubusercontent.com/25662450/102038403-21089780-3e02-11eb-9913-3d96c4d45291.png)
具体可以看一下docz的配置哈，https://www.docz.site/docs/project-configuration

**Comment by worldzhao** [comment]
站点工具由 docz 换成了 dumi，配置更方便了，同时更新了部署到 github pages 以及通过 github actions 自动触发构建部署的内容。具体可以看这个 issue 后半部分。
https://github.com/worldzhao/blog/issues/4
