### ISSUE TITLE
doz构建静态网站时，组件样式没有打包进去

### ISSUE THREAD

**Issue by rocspring** [worldzhao/react-ui-library-tutorial#13]
您好,

我按照流程搭建组件库，本地开发、组件库引用时，组件都正常展示。但是用`build:doc`打包静态网站后，组件的样式并没有打包到最后统一的css文件中，使得组件样式丢失。查了很久的文档，没发现是哪里的问题。想问一下，这个是需要什么配置项吗？

**Comment by worldzhao** [comment]
检查一下package.json中是否有配置sideEffects字段？





------------------ 原始邮件 ------------------
发件人: rocspring <notifications@github.com&gt;
发送时间: 2021年1月7日 14:29
收件人: worldzhao/react-ui-library-tutorial <react-ui-library-tutorial@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[worldzhao/react-ui-library-tutorial] doz构建静态网站时，组件样式没有打包进去 (#13)





 
您好,
 
我按照流程搭建组件库，本地开发、组件库引用时，组件都正常展示。但是用build:doc打包静态网站后，组件的样式并没有打包到最后统一的css文件中，使得组件样式丢失。查了很久的文档，没发现是哪里的问题。想问一下，这个是需要什么配置项吗？

**Comment by rocspring** [comment]
> 检查一下package.json中是否有配置sideEffects字段？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: rocspring <notifications@github.com&gt; 发送时间: 2021年1月7日 14:29 收件人: worldzhao/react-ui-library-tutorial <react-ui-library-tutorial@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[worldzhao/react-ui-library-tutorial] doz构建静态网站时，组件样式没有打包进去 (#13) 您好, 我按照流程搭建组件库，本地开发、组件库引用时，组件都正常展示。但是用build:doc打包静态网站后，组件的样式并没有打包到最后统一的css文件中，使得组件样式丢失。查了很久的文档，没发现是哪里的问题。想问一下，这个是需要什么配置项吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，确实是这个原因。不太熟悉，没想到是这里的配置。
