### ISSUE TITLE
部署后刷新页面会回到跟路由

### ISSUE THREAD

**Issue by ytudt** [worldzhao/react-ui-library-tutorial#14]
进入某个路由再刷新页面，会回到跟路由 这个有办法解决没？

**Comment by worldzhao** [comment]
由于 docz 大家碰到的问题太多了，所以站点工具从 docz 换成了 dumi，windows 同学应该不会出问题了，同时更新了部署到 github pages 以及通过 github actions 自动触发构建部署的内容。具体可以看这个 issue 后半部分。
https://github.com/worldzhao/blog/issues/4
