### ISSUE TITLE
部署后，页面打开会多发送请求，请求了文件目录

### ISSUE THREAD

**Issue by MAJIANYANG666** [worldzhao/react-ui-library-tutorial#16]
![image](https://user-images.githubusercontent.com/19359025/115232153-faa88f00-a148-11eb-97ae-2a4e8f4fffd3.png)

**Comment by MAJIANYANG666** [comment]
fe/new-touch-compoents时文件目录。不知道为啥部署后会发这样的请求。其他的请求却都是可以请求达到资源的

**Comment by worldzhao** [comment]
不好意思现在才回复。由于 docz 大家碰到的问题太多了，所以站点工具从 docz 换成了 dumi，同时更新了部署到 github pages 以及通过 github actions 自动触发构建部署的内容。具体可以看这个 issue 后半部分。
worldzhao/blog#4
