### ISSUE TITLE
能写一下如何部署吗

### ISSUE THREAD

**Issue by MAJIANYANG666** [worldzhao/react-ui-library-tutorial#17]

**Comment by worldzhao** [comment]
不好意思现在才回复。
文章更新了哈，有你需要的内容。
站点工具从 docz 换成了 dumi，同时更新了部署到 github pages 以及通过 github actions 自动触发构建部署的内容。具体可以看这个 issue 后半部分。
https://github.com/worldzhao/blog/issues/4
