### ISSUE TITLE
用npm安装报警告，启动报错

### ISSUE THREAD

**Issue by yangjinjun3** [worldzhao/react-ui-library-tutorial#23]
截图如下：

<img width="1171" alt="22222" src="https://user-images.githubusercontent.com/44964193/142416414-b9937f04-199e-40b6-b21d-fabe4abcd1ca.png">

<img width="1047" alt="111" src="https://user-images.githubusercontent.com/44964193/142416298-5622f92c-a16e-4ffa-af10-090ed05e681e.png">

**Comment by worldzhao** [comment]
考虑一下使用 yarn 安装依赖，仓库的 lockfile是 yarn 生成的，不保证 npm 能装到正确的依赖哈。
