### ISSUE TITLE
为啥执行build:site后生成的doc-site文件夹的index.html中没有css和js链接呢

### ISSUE THREAD

**Issue by yangjinjun3** [worldzhao/react-ui-library-tutorial#24]
想在公司部署，期望像单页面应用那样，生成的index.html中带有js和css链接

为啥执行build:site后生成的doc-site文件夹的index.html中没有css和js链接

**Comment by worldzhao** [comment]
确认一下是不是 dumi 配置问题，build:site 直接使用的 dumi build，预期就是单页应用，无法排查的话可以提个一个最小复现仓库我来看看

**Comment by yangjinjun3** [comment]
如果部署到我们自己的服务器上，是不是 _demos 和 ~demos 文件夹必须也上传，现在是不上传这俩文件夹，会报 umi.js 404。

如果不上传这俩文件夹，是否有其他解决方案，我们的服务器不支持 ～ / 这些特殊符号！

**Comment by worldzhao** [comment]
> 如果部署到我们自己的服务器上，是不是 _demos 和 ~demos 文件夹必须也上传，现在是不上传这俩文件夹，会报 umi.js 404。
> 
> 如果不上传这俩文件夹，是否有其他解决方案，我们的服务器不支持 ～ / 这些特殊符号！

只用上传 dumi 的打包产物就可以了，里面我看了下 只有 _ ，没有 ~ 和 / 的符号，应该没问题

**Comment by yangjinjun3** [comment]
我再看看，应该是我自己的问题

**Comment by yangjinjun3** [comment]
您好，我部署上去了，但是快速上手，组件，logo等所有链接走的都是根路径，请问这些路径我怎么配置成我想要的呢？

**Comment by yangjinjun3** [comment]
您好，我部署上去了，但是快速上手，组件等链接（比如 http://xxx.com/aaa/bbb/getting-started）一刷新都404了，进入他们自己的index.html地址也显示的不对，请问是我那儿配置的不对吗？


.urmirc里的base和publicPath配置的都是  /aaa/bbb
如果部署到域名根目录，应该没问题，但是一旦部署到 /aaa/bbb 子目录下，就出现此问题

还有如果方便我能加下你微信否，这个比较着急，多谢，我手机号 18310099497！

**Comment by worldzhao** [comment]
exportStatic: {}, 这个配置有没有

**Comment by yangjinjun3** [comment]
有的

<img width="508" alt="111111" src="https://user-images.githubusercontent.com/44964193/143156141-bca4e070-f430-43ba-a044-598b88c9ce2b.png">

**Comment by worldzhao** [comment]
> 有的
> 
> <img alt="111111" width="508" src="https://user-images.githubusercontent.com/44964193/143156141-bca4e070-f430-43ba-a044-598b88c9ce2b.png">

应该是操作有误，打包出来会生成很多的 html 文件，可以理解为单页 + 多页应用（js 跳转是单页，刷新是多页），刷新的时候会命中相应的 html 不会出现 404，看看是不是漏传文件了

**Comment by yangjinjun3** [comment]
我把您的master代码clone下来，只是在package.json中加了publicPath，还是有上述问题。

package.json：
"publicPath": "//xxx.com/react-ui-library-tutorial/",

**Comment by worldzhao** [comment]
> 我把您的master代码clone下来，只是在package.json中加了publicPath，还是有上述问题。
> 
> package.json： "publicPath": "//xxx.com/react-ui-library-tutorial/",

没太理解这个行为的目的，pacakge.json 里的这个字段有什么意义吗

**Comment by yangjinjun3** [comment]
我是想把代码部署到这个网址目录下
