### ISSUE TITLE
node_modules 删掉重装 在执行yarn build:types 会疯狂报错

### ISSUE THREAD

**Issue by hzh11012** [worldzhao/react-ui-library-tutorial#26]

**Comment by hzh11012** [comment]
tsconfig.build.json中换成如下即可

{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "emitDeclarationOnly": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true
  },
  "exclude": ["**/__tests__/**", "**/demo/**", "node_modules", "lib", "esm"]
}

**Comment by worldzhao** [comment]
时间久了依赖可能有问题了，换成 pnpm 处理了一下，然后 tsconfig.json 里加上 "skipLibCheck": true 应该就没问题了，感谢指出。
