### ISSUE TITLE
 ERROR #98123  WEBPACK

### ISSUE THREAD

**Issue by DBznhaung** [worldzhao/react-ui-library-tutorial#3]
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Unexpected token (17:40)

File: ../node_modules/_gatsby-theme-docz@2.3.1@gatsby-theme-docz/src/base/Layout.js:17:40

failed Building development bundle - 7.341s

git clone  后npm i  启动项目报错

**Comment by worldzhao** [comment]
hello，请用yarn安装依赖，仓库的.lock文件是yarn形式的。
