### ISSUE TITLE
package.json 中 为什么可以直接运行 ts？

### ISSUE THREAD

**Issue by git-lt** [worldzhao/react-ui-library-tutorial#4]
```json
{
 "new": "plop --plopfile ./scripts/plopfile.ts",
}
```
npm run new
这里为什么能直接运行ts，有什么配置吗？

**Comment by git-lt** [comment]
另外组件命名为什么要用  `kebabCase` 而不用 `pascalCase` 命名

**Comment by worldzhao** [comment]
> ```json
> {
>  "new": "plop --plopfile ./scripts/plopfile.ts",
> }
> ```
> 
> npm run new
> 这里为什么能直接运行ts，有什么配置吗？

plop自身支持typescript形式的配置文件，可以参见文档：https://github.com/plopjs/plop#typescript-declarations。 顺带提一嘴，release脚本也是ts形式，不过是使用ts-node执行的。

**Comment by worldzhao** [comment]
> 另外组件命名为什么要用 `kebabCase` 而不用 `pascalCase` 命名

这个命名属于我的个人习惯哈，统一就好。

**Comment by git-lt** [comment]
我本地试了一下， plop 不能直接运行 ts 文件，文档里只是说它有 ts 类型定义，你那边是不是将 ts-node 做了默认的 node 命令呢

**Comment by worldzhao** [comment]
> 我本地试了一下， plop 不能直接运行 ts 文件，文档里只是说它有 ts 类型定义，你那边是不是将 ts-node 做了默认的 node 命令呢

plop这个运行和本地的ts-node没有关系的哈，他的确是可以使用typescript配置文件。

原理是使用了interpret处理各种扩展类型以及相应的parser，对于ts来讲就是ts-node，可以看看哈。

- [interpret](https://github.com/gulpjs/interpret)
- [js-liftoff](https://github.com/js-cli/js-liftoff)

![plop](https://tva1.sinaimg.cn/large/007S8ZIlgy1geyrm2n6q1j30ie09ydh7.jpg)

**Comment by git-lt** [comment]
看了一下，是没有安装 ts-node与 typescript 到 deps 
十分感谢，从掘金来的，教程十分详细，收货很多

**Comment by zgsgs** [comment]
装了 ts-node 和 typescript 也运行不了 plop

**Comment by worldzhao** [comment]
> 装了 ts-node 和 typescript 也运行不了 plop

运行 plop 和这两个没有关系，plop 是自己解析 ts 文件并运行的 通过类似 bebel register 的库做到的

**Comment by zgsgs** [comment]
我补充一下, 需要指定版本为 plop@2.6.0 ,确实和 typescript、ts-node 没关系 按下面两步操作就行了

![image](https://user-images.githubusercontent.com/22882957/167101233-1a677dc9-7155-4b4d-b890-f3497a61eef9.png)
