### ISSUE TITLE
有两个问题想请教

### ISSUE THREAD

**Issue by 18518300669** [worldzhao/react-ui-library-tutorial#5]
1.在doc的mdx中这样引入css
```
import './style'
```
在开发环境中，样式可以用，但在build之后，部署到github，样式会没得到引用。

2.关于icon组件，使用svg-sprite-loader方式，在gatsby-config文件写入gatsby-plugin-svg-sprite，同样，在本地开发环境起作用，但是在build之后，并不会好用。

请问，这两个问题能帮忙分析下是为什么吗？

**Comment by worldzhao** [comment]
这两种情况大概率是package.json的sideEffects字段配置有误，可以详细了解一下。

**Comment by worldzhao** [comment]
sideEffects字段是为了做组件库的tree shaking，用户生产环境打包的时候会移除掉引用但未使用的文件（style.ts当然属于此类），由于只配置了lib esm 和dist三个文件夹所以这三个文件夹下面不会删除。但是我们的文档项目也相当于一个应用程序，所以把自己的样式给摇掉了，可以看看怎么绕过去，我是使用css in js方案，当然 也可以在sideEffects里加入更多路径，希望可以帮助到你。

**Comment by worldzhao** [comment]
sideEffects字段是为了做组件库的tree shaking，用户生产环境打包的时候会移除掉引用但未使用的文件（style.ts当然属于此类），由于只配置了lib esm 和dist三个文件夹所以这三个文件夹下面不会删除。

我们的文档项目也相当于一个应用程序，所以把自己的样式给摇掉了...可以：
1. 删除掉sideEffects字段（毕竟使用了babel-plugin-import，所以有些鸡肋）
2.给sideEffects字段增加配置，避免删除样式

由于我在公司内部使用的css in js方案所以不会出现这种情况，的确是我疏忽了

**Comment by worldzhao** [comment]
`sideEffects`字段是为了做组件库的`tree shaking`，用户生产环境打包的时候会移除掉引用但未使用的文件（style.ts当然属于此类），由于只配置了`lib` `esm` 和`dist`三个文件夹，故这三个文件夹下面不会删除。

我们的文档项目也相当于一个应用程序，所以把自己的样式给摇掉了...可以：
- 删除掉`sideEffects`字段（毕竟使用了`babel-plugin-import`，显得`sideEffects`有些鸡肋）
- 给`sideEffects`字段增加`components/**/style/**`等文件夹，避免删除其内样式，但作为`npm`包这个配置是多余的，只是为了文档样式不丢失，不如全删掉

由于我在公司内部使用的`css in js`方案所以不会出现这种情况（不会存在引用但未使用的脚本文件），的确是我疏忽了，感谢提问指出问题。

**Comment by 18518300669** [comment]
果然，如你所说，是这个问题导致的。关于这个问题，我的思路一直想偏了，一直在寻找docz的本地和开发的差异。
非常感谢，困扰我好几天了。
地址发来，外卖奶茶奉上。

**Comment by worldzhao** [comment]
> 果然，如你所说，是这个问题导致的。关于这个问题，我的思路一直想偏了，一直在寻找docz的本地和开发的差异。
> 非常感谢，困扰我好几天了。
> 地址发来，外卖奶茶奉上。

哈哈，本来就是我没写清楚，仓库代码也有问题，不用不用啦，能帮到你就好！
