### ISSUE TITLE
预览失败

### ISSUE THREAD

**Issue by hexianzhi** [worldzhao/react-ui-library-tutorial#7]
跑起来后是这样的：
![image](https://user-images.githubusercontent.com/11190425/88753723-8c253a80-d18f-11ea-9f81-2cd4d057566c.png)

**Comment by worldzhao** [comment]
> 跑起来后是这样的：
> ![image](https://user-images.githubusercontent.com/11190425/88753723-8c253a80-d18f-11ea-9f81-2cd4d057566c.png)

请问是windows平台吗，docz在windows平台存在[Bug](https://github.com/doczjs/docz/issues/1310)，暂未修复，建议使用WSL + VSCode运行本项目，避免环境影响。

**Comment by worldzhao** [comment]
由于 docz 大家碰到的问题太多了，所以站点工具从 docz 换成了 dumi，windows 同学应该不会出问题了，同时更新了部署到 github pages 以及通过 github actions 自动触发构建部署的内容。具体可以看这个 issue 后半部分。
worldzhao/blog#4
