### ISSUE TITLE
引用antd二次封装之后，在yarn build 报错

### ISSUE THREAD

**Issue by wumiangithub** [worldzhao/react-ui-library-tutorial#9]
node_modules/rc-field-form/es/Form.d.ts:20:27 - error TS2694: Namespace 'React' has no exported member 'ForwardRefRenderFunction'

**Comment by worldzhao** [comment]
我还没有尝试过在本项目中进行二次封装，看样子是ts类型声明生成问题，跳过类型声明应该可以，但不是好法子，有最小复现仓库吗，我也捣鼓捣鼓，共同学习一起交流

**Comment by lengkaixin** [comment]
求楼主大佬，看看引用antd二次封装后不能打包等等问题，现在业务有这么一个需求😬

**Comment by worldzhao** [comment]
1. 项目里增加`antd`作为`peerDependencies`以及`devDependencies`
2. tsconfig.json中的`compilerOptions`增加"skipLibCheck": true
3. 组件中使用按需形式引入antd组件
